### ISSUE TITLE
0.16 compatibility

### ISSUE THREAD

**Issue by molbi** [MrGuffels/World-of-Robots#9]
Hi, i will be possible make this addon for 0.16 version of game? Thx

edited: 

I have made changes to get it working for 0.16 and i can make PR with changes if you want. Missing icon_size property and buffer chest in definition :)

**Comment by HenryLoenwind** [comment]
Licence is MIT, so you can fork the project on github and even upload a 1.16 to the mod portal if the original author is not interested anymore.

I'd certainly be interested---playing with robots instead of belts from the beginning may be fun.

**Comment by MrGuffels** [comment]
11 months later LUL. It's updated.
